baseURL: "https://ste29.github.io/"
title: Data Centric World
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true
    
# To use html tags
markup:
    markup.goldmark:
        markup.goldmark.renderer:
            unsafe: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Data Centric World
    description: "Data science and data engineer notes"
    keywords: [Blog, Portfolio, PaperMod]
    author: Stefano
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon.ico"
        favicon32x32: "/favicon.ico"
        apple_touch_icon: "/favicon.ico"
        safari_pinned_tab: "/favicon.ico"

    label:
        text: "Home"
        icon: "/favicon.ico"
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Categories
              url: categories
            - name: Tags
              url: tags
            - name: Who Am I
              url: whoami

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: This blog is a sort "knowledge stash". A log of my journey in the consulting industry. You will find a variety of posts from Data Science to Data Engineering, from the classical machine learning approaches to the latest data architecture pattern.

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/stefano-villata-0b6368126/"
        #- name: stackoverflow
        #  url: "https://stackoverflow.com/users/3467733/justin"
        - name: github
          url: "https://github.com/Ste29"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/Ste29/ste29.github.io/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: tags
          name: tags
          url: /tags/
          weight: 10
        - identifier: categories
          name: categories
          url: /categories/
        - identifier: whoam
          name: whoami
          url: https://github.com/Ste29/blog-dev/tree/main/static/CV-Villata-Stefano.pdf
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai